### ISSUE TITLE
DNS SRV instancer doesn't deal well with missing port number

### ISSUE THREAD

**Issue by bboreham** [go-kit/kit#892]
It appears the Kubernetes DNS server will return 0 in the port number slot under some circumstances (most of the ones I tried), and `dnssrv/instancer.go` turns this into `:0` on the address.

Am I holding it wrong, or would you accept a PR to pass back the bare name if the port is 0?

**Comment by peterbourgon** [comment]
I find that strange; isn't an SRV record [explicitly meant to contain a port](https://en.wikipedia.org/wiki/SRV_record)? Can e.g. net.Dial possibly succeed without a one?

**Comment by bboreham** [comment]
Looks like if I name the port and look it up by name then I get the number; otherwise zero.

```
$ nslookup -type=SRV _http._tcp.distributor-h.cortex.svc.cluster.local. 10.244.218.156
Server:		10.244.218.156
Address:	10.244.218.156#53

_http._tcp.distributor-h.cortex.svc.cluster.local	service = 10 50 80 3630646565633364.distributor-h.cortex.svc.cluster.local.
_http._tcp.distributor-h.cortex.svc.cluster.local	service = 10 50 80 6563396264376365.distributor-h.cortex.svc.cluster.local.

$ nslookup -type=SRV distributor-h.cortex.svc.cluster.local. 10.244.218.156
Server:		10.244.218.156
Address:	10.244.218.156#53

distributor-h.cortex.svc.cluster.local	service = 10 50 0 3630646565633364.distributor-h.cortex.svc.cluster.local.
distributor-h.cortex.svc.cluster.local	service = 10 50 0 6563396264376365.distributor-h.cortex.svc.cluster.local.
```

service definition:
```
apiVersion: v1
kind: Service
metadata:
  name: distributor-h
  namespace: cortex
spec:
  clusterIP: None
  ports:
    - port: 80
      name: http
  selector:
    name: distributor
```
